# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js image
FROM node:20 AS build

# Set working directory
WORKDIR /app

# Copy source code and package.json
COPY . .

# Install pnpm globally
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install

# Build the project
RUN pnpm run build

# Use a smaller Node.js image for running the server
FROM node:20-slim

# Set working directory
WORKDIR /app

# Copy built files from the build stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/pnpm-lock.yaml ./pnpm-lock.yaml

# Install production dependencies
RUN npm install -g pnpm && pnpm install --prod

# Set environment variables (replace with your actual credentials)
ENV ESA_API_KEY=your_api_key
ENV DEFAULT_ESA_TEAM=your_default_team

# Expose port (if applicable, otherwise omit this line)
EXPOSE 3000

# Start the server
ENTRYPOINT ["node", "dist/index.js"]